### ISSUE TITLE
Leafpic gets killed while showing splash screen

### ISSUE THREAD

**Issue by undu** [UnevenSoftware/LeafPic#128]
I downloaded Leafpic from FDroid, but I only see the splash screen after I give permission to access the pictures.

Using Android Studio, this is what Android Monitor spews out:

```
961-4861/system_process E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 702280)
961-4861/system_process W/ActivityManager: Exception in new application when starting activity com.horaapps.leafpic/.MainActivity
    android.os.TransactionTooLargeException: data parcel size 702280 bytes
    at android.os.BinderProxy.transactNative(Native Method)
    at android.os.BinderProxy.transact(Binder.java:503)
    at android.app.ApplicationThreadProxy.scheduleLaunchActivity(ApplicationThreadNative.java:826)
    at com.android.server.am.ActivityStackSupervisor.realStartActivityLocked(ActivityStackSupervisor.java:1323)
    at com.android.server.am.ActivityStackSupervisor.attachApplicationLocked(ActivityStackSupervisor.java:647)
    at com.android.server.am.ActivityManagerService.attachApplicationLocked(ActivityManagerService.java:6432)
    at com.android.server.am.ActivityManagerService.attachApplication(ActivityManagerService.java:6495)
    at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:507)
    at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2670)
    at android.os.Binder.execTransact(Binder.java:453)
961-4861/system_process E/ActivityManager: Exception thrown launching activities in ProcessRecord{31bb989 21574:com.horaapps.leafpic/u0a150}
    android.os.TransactionTooLargeException: data parcel size 702280 bytes
    at android.os.BinderProxy.transactNative(Native Method)
    at android.os.BinderProxy.transact(Binder.java:503)
    at android.app.ApplicationThreadProxy.scheduleLaunchActivity(ApplicationThreadNative.java:826)
    at com.android.server.am.ActivityStackSupervisor.realStartActivityLocked(ActivityStackSupervisor.java:1323)
    at com.android.server.am.ActivityStackSupervisor.attachApplicationLocked(ActivityStackSupervisor.java:647)
    at com.android.server.am.ActivityManagerService.attachApplicationLocked(ActivityManagerService.java:6432)
    at com.android.server.am.ActivityManagerService.attachApplication(ActivityManagerService.java:6495)
    at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:507)
    at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2670)
    at android.os.Binder.execTransact(Binder.java:453)
961-4861/system_process I/ActivityManager: Killing 21574:com.horaapps.leafpic/u0a150 (adj 0): error during init
961-4861/system_process I/ActivityManager: Start proc 21587:com.horaapps.leafpic/u0a150 for activity com.horaapps.leafpic/.MainActivity
961-1648/system_process W/ActivityManager: Spurious death for ProcessRecord{31bb989 0:com.horaapps.leafpic/u0a150}, curProc for 21574: null
```

Don't know if it matters, I'm using CM13 (android 6.0.1) on a moto g 4g

Any ideas on how to debug this matter and get to the bottom of it?

**Comment by dnldsht** [comment]
Can i know how many albums do you have?

**Comment by undu** [comment]
In the Gallery app there 940

**Comment by dnldsht** [comment]
Great, I will look for a solution

**Comment by g1lg1l** [comment]
fixxed in this [release](https://github.com/HoraApps/LeafPic/releases/tag/v0.3.1)!

**Comment by undu** [comment]
Great! can confirm the bug is fixed!
