### ISSUE TITLE
LeafPic crashes (unfortunately has stopped) when started from within Open Camera app

### ISSUE THREAD

**Issue by iasgair** [UnevenSoftware/LeafPic#130]
First of all, great to see the development of a FOSS gallery app. Thanks to all who are involved, it looks great.

I use Open Camera (http://opencamera.sourceforge.net) as my standard camera app; when I tap on the gallery icon within Open Camera, it tries to open LeafPic, but I get the error message "Unfortunately, LeafPic has stopped."

It works fine with another gallery app (F-Stop), but that is not open source so it like to get rid of it.

Fairphone 2, android 5.1, not rooted, all google apps and services disabled

**Comment by iasgair** [comment]
I should add: I use LeafPic v0.2.6 from F-Droid.

**Comment by Astyan-42** [comment]
I have the same issue with the same version
Android 5.1, wiko pulp 4G, rooted, only the playstore as google app

**Comment by yenon** [comment]
Can reproduce on Android 6, here's the stacktrace:

java.lang.RuntimeException: Unable to resume activity {com.horaapps.leafpic/com.horaapps.leafpic.PhotoPagerActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.RelativeLayout.setBackgroundColor(int)' on a null object reference
    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3137)
    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3168)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2515)
    at android.app.ActivityThread.-wrap11(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5461)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:133)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.RelativeLayout.setBackgroundColor(int)' on a null object reference
    at com.horaapps.leafpic.PhotoPagerActivity.setupUI(PhotoPagerActivity.java:199)
    at com.horaapps.leafpic.PhotoPagerActivity.onResume(PhotoPagerActivity.java:229)
    at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1259)
    at android.app.Activity.performResume(Activity.java:6327)
    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3126)
    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3168)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2515)
    at android.app.ActivityThread.-wrap11(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5461)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:133)

I'm using XPosed, although that shouldn't be an issue. It seems that your UI hasn't been loaded (correctly) before you are changing the background color.

**Comment by rugk** [comment]
I also have this issue, but not only when using OpenCamera. It generally happens when I try to share (or better: open) a picture with my default gallery app and LeafPic crashes.

**Comment by poVoq** [comment]
Same issue here with a ASUS Zenfone2 (x86) running Android 5.0. Both OpenCamera and Leafpic are the latest versions from F-droid. I have disabled the Google gallery app if that makes a difference.

**Comment by ghost** [comment]
Same here. Version is 0.2.7 from fdroid. App crashes when opening a photo from inside opencamera. Phone is xperia z3 compact. 

Thanks for this great app. 
Regards

**Comment by revuwa** [comment]
I have the same issue (crash) on my Samsung i9300 @ AOSP 6.0.1 if I open pictures from external apps like Open Camera or Amaze (file manager).

Thanks a lot for looking into this.

**Comment by taranarmo** [comment]
Upgraded OpenCamera and LeafPic and everything works fine now.
Motorola Defy+, Android 4.4.4.

**Comment by taranarmo** [comment]
Upgraded OpenCamera and LeafPic and everything works fine now.
Motorola Defy+, Android 4.4.4.

**Comment by dnldsht** [comment]
nice!
