### ISSUE TITLE
Crash upon selecting any picture in camera folder

### ISSUE THREAD

**Issue by unsourced** [UnevenSoftware/LeafPic#144]
In version 0.2.6 I can no longer view any images in my camera folder (100MEDIA). This was not an issue in 0.2.5 (I would test this again but fdroid is giving me errors when I try to downgrade). The app still loads up images from other folders just fine, so I suspect this might be related to the large size of my camera folder (over 4000 images). When I click on an image in this folder the app gives me the Android 6.0 close app animation (app moves to the bottom of the screen) and if I return to the app through the recents menu its loads up the splash screen and starts again.

**Comment by dnldsht** [comment]
I fixed the limit image/albums issue also now i fetch images directly from the storage and non more from the MediaStore.

can you tell me what device do you own and give me the full path of your camera folder?

**Comment by unsourced** [comment]
HTC One M8 on android 6.0. In my file explorer I can reach the folder through both /sdcard/DCIM/100MEDIA and /storage/emulated/0/DCIM/100MEDIA.

(As a side note, since I'm not sure if this is related or a separate bug. In v0.2.7 the app crashes when selecting the "Excluded Albums" option in settings.)

Edit: I got the "excluded albums" option working again by clearing user data on the app. I can now see that the app is finding the camera folder through: /storage/emulated/0/DCIM/100MEDIA

**Comment by unsourced** [comment]
Ok just found something else out, hope it is useful. I can open up images in the folder when I filter for image or video, since this lowers the number of images in the folder. (The filter seems to stick even though the filter menu keeps showing "all"). So I tested the folder size by deleting and adding photos. It seems that whenever LeafPic lists the folder as having "4103 Media" any photo crashes it, but when it has "4102 Media" I can open up all the pictures without problem. (I am not sure if this is related to the "limit image/albums issue" that you fixed.)

Strangely I think this might be based on the file quantity and not filesize, because it doesn't matter if the last media added to the folder (totaling 4102) is an image or (larger) video, they both work, but if the folder has 4103 items, no matter what it crashes. I also checked my file explorer but for some reason it detects a different number files in the folder. I am using Amaze File Explorer and it tells me for "4103 media"(can't open media): 2805 items 12.72GB folder size, and for when it is at "4102 media"(can open): 2804 items either 12.71GB (last item picture) or 12.73 (last item video). I'm not about to count the number of files in the folder, so I am not sure where the discrepancy is coming from.

**Comment by varunoberoi** [comment]
Happened to me as well. Looks like it occurs only when folder contains too many pictures (>2000). Here is the log:

```
java.lang.RuntimeException: Failure from system
                                                                        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1516)
                                                                        at android.app.Activity.startActivityForResult(Activity.java:3930)
                                                                        at android.app.Activity.startActivityForResult(Activity.java:3890)
                                                                        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:843)
                                                                        at android.app.Activity.startActivity(Activity.java:4213)
                                                                        at android.app.Activity.startActivity(Activity.java:4181)
                                                                        at com.horaapps.leafpic.MainActivity$2.onClick(MainActivity.java:118)
                                                                        at android.view.View.performClick(View.java:5204)
                                                                        at android.view.View$PerformClick.run(View.java:21156)
                                                                        at android.os.Handler.handleCallback(Handler.java:739)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at android.os.Looper.loop(Looper.java:148)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5456)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)


Caused by: android.os.TransactionTooLargeException: data parcel size 1075848 bytes
                                                                        at android.os.BinderProxy.transactNative(Native Method)
                                                                        at android.os.BinderProxy.transact(Binder.java:503)
                                                                        at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:2666)
                                                                        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1509)
                                                                        at android.app.Activity.startActivityForResult(Activity.java:3930) 
                                                                        at android.app.Activity.startActivityForResult(Activity.java:3890) 
                                                                        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:843) 
                                                                        at android.app.Activity.startActivity(Activity.java:4213) 
                                                                        at android.app.Activity.startActivity(Activity.java:4181) 
                                                                        at com.horaapps.leafpic.MainActivity$2.onClick(MainActivity.java:118) 
                                                                        at android.view.View.performClick(View.java:5204) 
                                                                        at android.view.View$PerformClick.run(View.java:21156) 
                                                                        at android.os.Handler.handleCallback(Handler.java:739) 
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                        at android.os.Looper.loop(Looper.java:148) 
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5456) 
                                                                        at java.lang.reflect.Method.invoke(Native Method) 
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```

**Comment by g1lg1l** [comment]
fixxed in this [release](https://github.com/HoraApps/LeafPic/releases/tag/v0.3.1)!:)
