### ISSUE TITLE
NPE Crash in MainActivity's onResume method when LeafPic was ejected from memory

### ISSUE THREAD

**Issue by xtj-9182** [UnevenSoftware/LeafPic#217]
again I'm on 04bf2801f81fbc22ac5b7ef69fc2fb164d8b5fd7 (probably works in v0.4 too)
on Android 6.0.1 @ LG G3
1. Start LeafPic normally and wait for it to finish loading
2. Bring LeafPic to the background by using some other apps
3. Don't use LeafPic until it gets ejected from Memory
4. Tap on LeafPic from the recent apps screen (it only works if LeafPic was ejected from memory)
5. LeafPic will call MainActivity's onResume method and crash

`java.lang.RuntimeException: Unable to resume activity {com.horaapps.leafpic/com.horaapps.leafpic.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.horaapps.leafpic.Base.HandlingAlbums.clearSelectedAlbums()' on a null object reference
                                                                          at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3137)
                                                                          at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3168)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2515)
                                                                          at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:148)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5461)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                       Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.horaapps.leafpic.Base.HandlingAlbums.clearSelectedAlbums()' on a null object reference
                                                                          at com.horaapps.leafpic.MainActivity.onResume(MainActivity.java:209)
                                                                          at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1259)
                                                                          at android.app.Activity.performResume(Activity.java:6327)
                                                                          at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3126)
                                                                          at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3168) 
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2515) 
                                                                          at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                          at android.os.Looper.loop(Looper.java:148) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5461) 
                                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) `

this can be "fixed" by calling 
`albums = new HandlingAlbums(getApplicationContext());
 album = new Album();` 
before line 209 in MainActivity. This would then have the side effect of only showing an empty album but this is better than crashing I think

**Comment by dnldsht** [comment]
@xtj-9182 how were you able to get LeafPic ejected from the memory?

**Comment by xtj-9182** [comment]
My LG G3 was using pretty agressive minfree settings by default so after opening like 3-4 apps apps would start reloading, I have since adjusted my minfree settings and I struggle to reproduce this with the latest commit, so for now I'm closing this.
