### ISSUE TITLE
java.lang.IndexOutOfBoundsException Blank Gallery/No Media

### ISSUE THREAD

**Issue by squiggie** [UnevenSoftware/LeafPic#251]
Leafpic from Github
Android 6.0
Genymotion Emu

If the phone has no media on it, the application will crash on launch with the following error:

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.horaapps.leafpic/com.horaapps.leafpic.MainActivity}: java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
at android.app.ActivityThread.-wrap11(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
at java.util.ArrayList.get(ArrayList.java:308)
at com.horaapps.leafpic.Data.HandlingAlbums.getCurrentAlbum(HandlingAlbums.java:88)
at com.horaapps.leafpic.MyApplication.getCurrentAlbum(MyApplication.java:16)
at com.horaapps.leafpic.Views.SharedMediaActivity.getAlbum(SharedMediaActivity.java:24)
at com.horaapps.leafpic.MainActivity.initUI(MainActivity.java:372)
at com.horaapps.leafpic.MainActivity.onCreate(MainActivity.java:186)
at android.app.Activity.performCreate(Activity.java:6237)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
at android.app.ActivityThread.-wrap11(ActivityThread.java) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
at android.os.Handler.dispatchMessage(Handler.java:102) 
at android.os.Looper.loop(Looper.java:148) 
at android.app.ActivityThread.main(ActivityThread.java:5417) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```

This is because current = 0 in 

``` java
  public Album getCurrentAlbum() {
    return dispAlbums.get(current);
  }
```

You can also reproduce this by deleting all the photos on your phone from within the app and relaunching the app.

**Comment by dnldsht** [comment]
do you have this issue also on v0.5.2?

**Comment by squiggie** [comment]
Unfortunately I cannot get develop branch compiled. I'm getting this error:  
Error:Cause: com/android/build/gradle/internal/model/DefaultAndroidProject : Unsupported major.minor version 52.0

I've tried setting everything up to run Java 1.8 but I cannot get past this error.

**Comment by squiggie** [comment]
I was able to get this to build using the classpath 'com.android.tools.build:gradle:2.1.3' instead of the alpha. 

Anyway, I believe this bug is fixed in the develop build due to this code. 

``` java
public Album getCurrentAlbum() {
    return albums.dispAlbums.size() > 0 ? albums.getCurrentAlbum() : new Album();
}
```

The previous master I don't think was returning a new Album.
