### ISSUE TITLE
Crashing on startup

### ISSUE THREAD

**Issue by RayManning** [UnevenSoftware/LeafPic#344]
Leafpic unfortunately stops shortly after pressing the application icon. I'm on KitKat 4.4.2

**Comment by schaal** [comment]
Same here, the logcat shows the following stacktrace:

```
FATAL EXCEPTION: main
Process: org.horaapps.leafpic, PID: 10378
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.horaapps.leafpic/org.horaapps.leafpic.activities.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'org.horaapps.leafpic.data.base.FilterMode org.horaapps.leafpic.data.AlbumSettings.getFilterMode()' on a null object reference
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2426)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490)
    at android.app.ActivityThread.-wrap11(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5443)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'org.horaapps.leafpic.data.base.FilterMode org.horaapps.leafpic.data.AlbumSettings.getFilterMode()' on a null object reference
    at org.horaapps.leafpic.data.Album.getMedia(Album.java:81)
    at org.horaapps.leafpic.activities.MainActivity.initUI(MainActivity.java:313)
    at org.horaapps.leafpic.activities.MainActivity.onCreate(MainActivity.java:175)
    at android.app.Activity.performCreate(Activity.java:6245)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1130)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490) 
    at android.app.ActivityThread.-wrap11(ActivityThread.java) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354) 
    at android.os.Handler.dispatchMessage(Handler.java:102) 
    at android.os.Looper.loop(Looper.java:148) 
    at android.app.ActivityThread.main(ActivityThread.java:5443) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618) 
```

**Comment by mvevitsis** [comment]
Same here.

**Comment by oldastar** [comment]
Doogee Dager 550 Android 4.4.2
Working 08/16-09/16.
Now no start app, stoped after press icon.
edit - 0.5.2 working

**Comment by phuyuk** [comment]
Same here.

**Comment by dnldsht** [comment]
@phuyuk are you on the v0.6-beta-1?

**Comment by phuyuk** [comment]
F-Droid v0.6-beta-1 (on 4.4.2)

**Comment by oldastar** [comment]
All version from Fdroid stoped, from here *withGplay, *noGP stuped too. Working only org.horaapps.leafpic_v0.5.2-10_minAPI19(nodpi)_apkmirror.com.app

**Comment by Micha-Btz** [comment]
happens to me too. Version 0.6-beta-1 from f-droid store. Cyanogenmod CM-12.1.

```
--------- beginning of crash
10-17 14:39:26.029 E/AndroidRuntime(10559): FATAL EXCEPTION: main
10-17 14:39:26.029 E/AndroidRuntime(10559): Process: org.horaapps.leafpic, PID: 10559
10-17 14:39:26.029 E/AndroidRuntime(10559): java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
10-17 14:39:26.029 E/AndroidRuntime(10559):     at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
10-17 14:39:26.029 E/AndroidRuntime(10559):     at java.util.ArrayList.get(ArrayList.java:308)
10-17 14:39:26.029 E/AndroidRuntime(10559):     at org.horaapps.leafpic.data.Album.getMedia(Album.java:217)
10-17 14:39:26.029 E/AndroidRuntime(10559):     at org.horaapps.leafpic.data.Album.getCurrentMedia(Album.java:223)
10-17 14:39:26.029 E/AndroidRuntime(10559):     at org.horaapps.leafpic.activities.SingleMediaActivity.onPrepareOptionsMenu(SingleMediaActivity.java:271)
10-17 14:39:26.029 E/AndroidRuntime(10559):     at android.app.Activity.onPreparePanel(Activity.java:2841)
10-17 14:39:26.029 E/AndroidRuntime(10559):     at android.support.v4.app.FragmentActivity.onPrepareOptionsPanel(FragmentActivity.java:547)
10-17 14:39:26.029 E/AndroidRuntime(10559):     at android.support.v4.app.FragmentActivity.onPreparePanel(FragmentActivity.java:536)
10-17 14:39:26.029 E/AndroidRuntime(10559):     at android.support.v7.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:93)
10-17 14:39:26.029 E/AndroidRuntime(10559):     at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.onPreparePanel(AppCompatDelegateImplBase.java:297)
10-17 14:39:26.029 E/AndroidRuntime(10559):     at android.support.v7.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:93)
10-17 14:39:26.029 E/AndroidRuntime(10559):     at android.support.v7.app.ToolbarActionBar$ToolbarCallbackWrapper.onPreparePanel(ToolbarActionBar.java:567)
10-17 14:39:26.029 E/AndroidRuntime(10559):     at android.support.v7.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:455)
10-17 14:39:26.029 E/AndroidRuntime(10559):     at android.support.v7.app.ToolbarActionBar$1.run(ToolbarActionBar.java:61)
10-17 14:39:26.029 E/AndroidRuntime(10559):     at android.os.Handler.handleCallback(Handler.java:739)
10-17 14:39:26.029 E/AndroidRuntime(10559):     at android.os.Handler.dispatchMessage(Handler.java:95)
10-17 14:39:26.029 E/AndroidRuntime(10559):     at android.os.Looper.loop(Looper.java:135)
10-17 14:39:26.029 E/AndroidRuntime(10559):     at android.app.ActivityThread.main(ActivityThread.java:5294)
10-17 14:39:26.029 E/AndroidRuntime(10559):     at java.lang.reflect.Method.invoke(Native Method)
10-17 14:39:26.029 E/AndroidRuntime(10559):     at java.lang.reflect.Method.invoke(Method.java:372)
10-17 14:39:26.029 E/AndroidRuntime(10559):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
10-17 14:39:26.029 E/AndroidRuntime(10559):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
10-17 14:39:26.080 W/ActivityManager(2236):   Force finishing activity 1 org.horaapps.leafpic/.activities.SingleMediaActivity
10-17 14:39:26.151 I/OpenGLRenderer(2236): Initialized EGL, version 1.4
10-17 14:39:26.582 W/ActivityManager(2236): Activity pause timeout for ActivityRecord{265c995a u0 org.horaapps.leafpic/.activities.SingleMediaActivity t1131 f}
10-17 14:39:26.584 V/WindowManager(2236): rotationForOrientationLw(orient=-1, last=0); user=0 
10-17 14:39:26.588 V/WindowManager(2236): Adding window Window{8b2d16c u0 Starting org.horaapps.leafpic} at 17 of 26 (before Window{15faa76b u0 org.horaapps.leafpic/org.horaapps.leafpic.activities.SingleMediaActivity})
```

maybe it helps to solve it. no gapps on phone.

**Comment by FroDar** [comment]
It was constantly crashing at startup on 6.1, now that I have a  7.0,  so far it hasn't crashed.

**Comment by andyrtr** [comment]
I had such crash when there was no picture at all. After the first photo taken and put there it opened well on Marshmallow. But maybe that's a different crash at startup.

**Comment by ghost** [comment]
same here on android 4.4.2...
