### ISSUE TITLE
Crash when resuming LeafPic after purge from memory

### ISSUE THREAD

**Issue by d4rken** [UnevenSoftware/LeafPic#398]
I opened LeafPic from my launcher shortcut, it tried to resume on a specific album or picture is viewed when I last had it open.

Opened fine when opening it again.

`Pixel 128GB @ 7.1.1`

Seems to happen everytime the UI is open on a sub album and the app has been removed from memory and is then restored.

```
03-22 13:09:20.586 E/AndroidRuntime(12672): FATAL EXCEPTION: main
03-22 13:09:20.586 E/AndroidRuntime(12672): Process: org.horaapps.leafpic.debug, PID: 12672
03-22 13:09:20.586 E/AndroidRuntime(12672): java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
03-22 13:09:20.586 E/AndroidRuntime(12672): 	at java.util.ArrayList.get(ArrayList.java:411)
03-22 13:09:20.586 E/AndroidRuntime(12672): 	at org.horaapps.leafpic.model.Album.getMedia(Album.java:166)
03-22 13:09:20.586 E/AndroidRuntime(12672): 	at org.horaapps.leafpic.model.Album.getCurrentMedia(Album.java:172)
03-22 13:09:20.586 E/AndroidRuntime(12672): 	at org.horaapps.leafpic.activities.SingleMediaActivity.onPrepareOptionsMenu(SingleMediaActivity.java:270)
03-22 13:09:20.586 E/AndroidRuntime(12672): 	at android.app.Activity.onPreparePanel(Activity.java:3160)
03-22 13:09:20.586 E/AndroidRuntime(12672): 	at android.support.v4.app.FragmentActivity.onPrepareOptionsPanel(FragmentActivity.java:535)
03-22 13:09:20.586 E/AndroidRuntime(12672): 	at android.support.v4.app.FragmentActivity.onPreparePanel(FragmentActivity.java:523)
03-22 13:09:20.586 E/AndroidRuntime(12672): 	at android.support.v7.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:103)
03-22 13:09:20.586 E/AndroidRuntime(12672): 	at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.onPreparePanel(AppCompatDelegateImplBase.java:362)
03-22 13:09:20.586 E/AndroidRuntime(12672): 	at android.support.v7.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:103)
03-22 13:09:20.586 E/AndroidRuntime(12672): 	at android.support.v7.app.ToolbarActionBar$ToolbarCallbackWrapper.onPreparePanel(ToolbarActionBar.java:567)
03-22 13:09:20.586 E/AndroidRuntime(12672): 	at android.support.v7.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:455)
03-22 13:09:20.586 E/AndroidRuntime(12672): 	at android.support.v7.app.ToolbarActionBar$1.run(ToolbarActionBar.java:61)
03-22 13:09:20.586 E/AndroidRuntime(12672): 	at android.os.Handler.handleCallback(Handler.java:751)
03-22 13:09:20.586 E/AndroidRuntime(12672): 	at android.os.Handler.dispatchMessage(Handler.java:95)
03-22 13:09:20.586 E/AndroidRuntime(12672): 	at android.os.Looper.loop(Looper.java:154)
03-22 13:09:20.586 E/AndroidRuntime(12672): 	at android.app.ActivityThread.main(ActivityThread.java:6119)
03-22 13:09:20.586 E/AndroidRuntime(12672): 	at java.lang.reflect.Method.invoke(Native Method)
03-22 13:09:20.586 E/AndroidRuntime(12672): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
03-22 13:09:20.586 E/AndroidRuntime(12672): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
03-22 13:09:20.588 W/ActivityManager(1103):   Force finishing activity org.horaapps.leafpic.debug/org.horaapps.leafpic.activities.SingleMediaActivity
```

**Comment by calvinnor** [comment]
@d4rken Thanks for reporting this issue!

I've fixed a bunch of crashes lately, including ones where LeafPic crashes when resuming from background. 
We'd love you to either build LeafPic from source, or wait for our next release!

Btw, awesome job with SD Maid :+1:

**Comment by CalvinNor** [comment]
#493
