### ISSUE TITLE
v0.6-beta-1: crash on appstart: android-4.4 does not contain/support "drawable ripple"

### ISSUE THREAD

**Issue by k3b** [UnevenSoftware/LeafPic#418]
LeafPic v0.5.9 uses code that is not supported by my android-4.4 cellphone

according to https://developer.android.com/reference/android/graphics/drawable/RippleDrawable.html
this requires android-api-21 or newer

callstack

	W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x41925ce0)
	W/dalvikvm: threadid=1: uncaught exception occurred
	W/System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.horaapps.leafpic/org.horaapps.leafpic.activities.MainActivity}: android.view.InflateException: Binary XML file line #63: Error inflating class <unknown>
	W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2338)
	W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2390)
	W/System.err:     at android.app.ActivityThread.access$800(ActivityThread.java:151)
	W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
	W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:110)
	W/System.err:     at android.os.Looper.loop(Looper.java:193)
	W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5299)
	W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
	W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
	W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825)
	W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641)
	W/System.err:     at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
	W/System.err:     at dalvik.system.NativeStart.main(Native Method)
	W/System.err: Caused by: android.view.InflateException: Binary XML file line #63: Error inflating class <unknown>
	W/System.err:     at android.view.LayoutInflater.createView(LayoutInflater.java:620)
	W/System.err:     at com.mikepenz.iconics.context.InternalLayoutInflater.onCreateView(InternalLayoutInflater.java:54)
	W/System.err:     at android.view.LayoutInflater.onCreateView(LayoutInflater.java:669)
	W/System.err:     at com.mikepenz.iconics.context.InternalLayoutInflater.onCreateView(InternalLayoutInflater.java:70)
	W/System.err:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:694)
	W/System.err:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
	W/System.err:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
	W/System.err:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
	W/System.err:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
	W/System.err:     at android.view.LayoutInflater.parseInclude(LayoutInflater.java:839)
	W/System.err:     at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
	W/System.err:     at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
	W/System.err:     at android.view.LayoutInflater.parseInclude(Native Method)
	W/System.err:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:745)
	W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
	W/System.err:     at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
	W/System.err:     at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
	W/System.err:     at android.view.LayoutInflater.inflate(Native Method)
	W/System.err:     at com.mikepenz.iconics.context.InternalLayoutInflater.inflate(InternalLayoutInflater.java:81)
	W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
	W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
	W/System.err:     at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280)
	W/System.err:     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
	W/System.err:     at org.horaapps.leafpic.activities.MainActivity.onCreate(MainActivity.java:168)
	W/System.err:     at android.app.Activity.performCreate(Activity.java:5264)
	W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088)
	W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2302)
	W/System.err: 	... 12 more
	W/System.err: Caused by: java.lang.reflect.InvocationTargetException
	W/System.err:     at java.lang.reflect.Constructor.constructNative(Native Method)
	W/System.err:     at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	W/System.err:     at android.view.LayoutInflater.createView(LayoutInflater.java:594)
	W/System.err: 	... 38 more
	W/System.err: Caused by: android.content.res.Resources$NotFoundException: File res/drawable/ripple.xml from drawable resource ID #0x7f020056
	W/System.err:     at android.content.res.Resources.loadDrawable(Resources.java:2152)
	W/System.err:     at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
	W/System.err:     at android.content.res.XResources$XTypedArray.getDrawable(XResources.java:965)
	W/System.err:     at android.view.View.<init>(View.java:3579)
	W/System.err:     at android.view.ViewGroup.<init>(ViewGroup.java:494)
	W/System.err:     at android.widget.LinearLayout.<init>(LinearLayout.java:188)
	W/System.err:     at android.widget.LinearLayout.<init>(LinearLayout.java:183)
	W/System.err: 	... 41 more
	W/System.err: Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #12: invalid drawable tag ripple
	W/System.err:     at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:933)
	W/System.err:     at android.graphics.drawable.Drawable.createFromXml(Drawable.java:877)
	W/System.err:     at android.content.res.Resources.loadDrawable(Resources.java:2148)
	W/System.err: 	... 47 more
	W/dalvikvm: threadid=1: calling UncaughtExceptionHandler
	E/AndroidRuntime: FATAL EXCEPTION: main
					  Process: org.horaapps.leafpic, PID: 13533
					  java.lang.RuntimeException: Unable to start activity ComponentInfo{org.horaapps.leafpic/org.horaapps.leafpic.activities.MainActivity}: android.view.InflateException: Binary XML file line #63: Error inflating class <unknown>
						  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2338)
						  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2390)
						  at android.app.ActivityThread.access$800(ActivityThread.java:151)
						  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
						  at android.os.Handler.dispatchMessage(Handler.java:110)
						  at android.os.Looper.loop(Looper.java:193)
						  at android.app.ActivityThread.main(ActivityThread.java:5299)
						  at java.lang.reflect.Method.invokeNative(Native Method)
						  at java.lang.reflect.Method.invoke(Method.java:515)
						  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825)
						  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641)
						  at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
						  at dalvik.system.NativeStart.main(Native Method)
					   Caused by: android.view.InflateException: Binary XML file line #63: Error inflating class <unknown>
						  at android.view.LayoutInflater.createView(LayoutInflater.java:620)
						  at com.mikepenz.iconics.context.InternalLayoutInflater.onCreateView(InternalLayoutInflater.java:54)
						  at android.view.LayoutInflater.onCreateView(LayoutInflater.java:669)
						  at com.mikepenz.iconics.context.InternalLayoutInflater.onCreateView(InternalLayoutInflater.java:70)
						  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:694)
						  at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
						  at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
						  at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
						  at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
						  at android.view.LayoutInflater.parseInclude(LayoutInflater.java:839)
						  at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
						  at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
						  at android.view.LayoutInflater.parseInclude(Native Method)
						  at android.view.LayoutInflater.rInflate(LayoutInflater.java:745)
						  at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
						  at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
						  at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
						  at android.view.LayoutInflater.inflate(Native Method)
						  at com.mikepenz.iconics.context.InternalLayoutInflater.inflate(InternalLayoutInflater.java:81)
						  at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
						  at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
						  at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280)
						  at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
						  at org.horaapps.leafpic.activities.MainActivity.onCreate(MainActivity.java:168)
						  at android.app.Activity.performCreate(Activity.java:5264)
						  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088)
						  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2302)
						  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2390) 
						  at android.app.ActivityThread.access$800(ActivityThread.java:151) 
						  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321) 
						  at android.os.Handler.dispatchMessage(Handler.java:110) 
						  at android.os.Looper.loop(Looper.java:193) 
						  at android.app.ActivityThread.main(ActivityThread.java:5299) 
						  at java.lang.reflect.Method.invokeNative(Native Method) 
						  at java.lang.reflect.Method.invoke(Method.java:515) 
						  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825) 
						  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641) 
						  at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132) 
						  at dalvik.system.NativeStart.main(Native Method) 
					   Caused by: java.lang.reflect.InvocationTargetException
						  at java.lang.reflect.Constructor.constructNative(Native Method)
						  at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
						  at android.view.LayoutInflater.createView(LayoutInflater.java:594)
						  at com.mikepenz.iconics.context.InternalLayoutInflater.onCreateView(InternalLayoutInflater.java:54) 
						  at android.view.LayoutInflater.onCreateView(LayoutInflater.java:669) 
						  at com.mikepenz.iconics.context.InternalLayoutInflater.onCreateView(InternalLayoutInflater.java:70) 
						  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:694) 
						  at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
						  at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
						  at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
						  at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
						  at android.view.LayoutInflater.parseInclude(LayoutInflater.java:839) 
						  at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method) 
						  at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631) 
						  at android.view.LayoutInflater.parseInclude(Native Method) 
						  at android.view.LayoutInflater.rInflate(LayoutInflater.java:745) 
						  at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
						  at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method) 
						  at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631) 
						  at android.view.LayoutInflater.inflate(Native Method) 
						  at com.mikepenz.iconics.context.InternalLayoutInflater.inflate(InternalLayoutInflater.java:81) 
						  at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
						  at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
						  at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280) 
						  at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
						  at org.horaapps.leafpic.activities.MainActivity.onCreate(MainActivity.java:168) 
						  at android.app.Activity.performCreate(Activity.java:5264) 
						  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088) 
						  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2302) 
						  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2390) 
						  at android.app.ActivityThread.access$800(ActivityThread.java:151) 
						  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321) 
						  at android.os.Handler.dispatchMessage(Handler.java:110) 
						  at android.os.Looper.loop(Looper.java:193) 
						  at android.app.ActivityThread.main(ActivityThread.java:5299) 
						  at java.lang.reflect.Method.invokeNative(Native Method) 
						  at java.lang.reflect.Method.invoke(Method.java:515) 
						  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825) 
						  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641) 
						  at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132) 
						  at dalvik.system.NativeStart.main(Native Method) 
					   Caused by: android.content.res.Resources$NotFoundException: File res/drawable/ripple.xml from drawable resource ID #0x7f020056
						  at android.content.res.Resources.loadDrawable(Resources.java:2152)
						  at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
						  at android.content.res.XResources$XTypedArray.getDrawable(XResources.java:965)
						  at android.view.View.<init>(View.java:3579)
						  at android.view.ViewGroup.<init>(ViewGroup.java:494)
						  at android.widget.LinearLayout.<init>(LinearLayout.java:188)
						at android.

**Comment by k3b** [comment]
with local build currend dev branch (2017-08-28) the issue does not exist any more. thanks for fixing
