### ISSUE TITLE
TransactionTooLargeException on Single Media Activity

### ISSUE THREAD

**Issue by harshmittal2810** [UnevenSoftware/LeafPic#457]
Hello there,
I am using dev branch and when I open a media file of image or video it's throwing this error,

Exception thrown launching activities in ProcessRecord{67b2060 1121:in.web2droid.galleryview.debug/u0a255}
                                                   android.os.TransactionTooLargeException: data parcel size 665888 bytes
                                                       at android.os.BinderProxy.transactNative(Native Method)
                                                       at android.os.BinderProxy.transact(Binder.java:628)
                                                       at android.app.ApplicationThreadProxy.scheduleLaunchActivity(ApplicationThreadNative.java:976)
                                                       at com.android.server.am.ActivityStackSupervisor.realStartActivityLocked(ActivityStackSupervisor.java:1738)
                                                       at com.android.server.am.ActivityStackSupervisor.attachApplicationLocked(ActivityStackSupervisor.java:1147)
                                                       at com.android.server.am.ActivityManagerService.attachApplicationLocked(ActivityManagerService.java:8831)
                                                       at com.android.server.am.ActivityManagerService.attachApplication(ActivityManagerService.java:8911)
                                                       at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:550)
                                                       at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3698)
                                                       at android.os.Binder.execTransact(Binder.java:573)

**Comment by dnldsht** [comment]
Known bug on dev branch will fix this soon. You got it opening an
image/video in a large folder right?

**Comment by harshmittal2810** [comment]
Yeah, I got ur new commit also.
Now working fine thanks
I am also want to contribute to this project.
