### ISSUE TITLE
Crash when resuming LeafPic in Media mode and pressing back

### ISSUE THREAD

**Issue by calvinnor** [UnevenSoftware/LeafPic#475]
LeafPic crashes when a user clicks on an album / folder, then minimizes the application. If the Activity is killed / Don't Keep Activities is enabled, the app crashes on back.

Here's the stack trace:

`
12-16 19:32:45.817 4061-4061/org.horaapps.leafpic.debug E/MessageQueue-JNI: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.horaapps.leafpic.adapters.AlbumsAdapter.selecting()' on a null object reference
                                                                                at org.horaapps.leafpic.fragments.AlbumsFragment.editMode(AlbumsFragment.java:504)
                                                                                at org.horaapps.leafpic.fragments.BaseFragment.onBackPressed(BaseFragment.java:13)
                                                                                at org.horaapps.leafpic.activities.MainActivity.onBackPressed(MainActivity.java:456)
                                                                                at android.app.Activity.onKeyUp(Activity.java:2753)
                                                                                at android.view.KeyEvent.dispatch(KeyEvent.java:2712)
                                                                                at android.app.Activity.dispatchKeyEvent(Activity.java:3054)
                                                                                at android.support.v7.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:534)
                                                                                at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:58)
                                                                                at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:316)
                                                                                at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:320)
                                                                                at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4396)
                                                                                at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4367)
                                                                                at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3911)
                                                                                at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3964)
                                                                                at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3930)
                                                                                at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4057)
                                                                                at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3938)
                                                                                at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4114)
                                                                                at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3911)
                                                                                at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3964)
                                                                                at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3930)
                                                                                at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3938)
                                                                                at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3911)
                                                                                at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3964)
                                                                                at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3930)
                                                                                at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4090)
                                                                                at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4251)
                                                                                at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2430)
                                                                                at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1994)
                                                                                at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1985)
                                                                                at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2407)
                                                                                at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
                                                                                at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                                at android.os.MessageQueue.next(MessageQueue.java:323)
                                                                                at android.os.Looper.loop(Looper.java:136)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:6422)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
`

**Comment by calvinnor** [comment]
@dnldsht I'm working on this issue. Seems to be a problem with saving instance state.
Will raise a fix by EOD.

**Comment by calvinnor** [comment]
@dnldsht Raised https://github.com/HoraApps/LeafPic/pull/476 for review.

**Comment by calvinnor** [comment]
@dnldsht Could you give me privileges to add tags / close issues?

This issue is fixed.
