### ISSUE TITLE
Video and Gif not able to play

### ISSUE THREAD

**Issue by harshmittal2810** [UnevenSoftware/LeafPic#484]
When I click on video and gif images. I got an error and I checked the file that file is correct format. Error log is like this:

Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
                                                                                  at android.support.v4.content.FileProvider.parsePathStrategy(FileProvider.java:591)
                                                                                  at android.support.v4.content.FileProvider.getPathStrategy(FileProvider.java:565)
                                                                                  at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:403)
                                                                                  at StorageHelper.getUriForFile(StorageHelper.java:113)

**Comment by calvinnor** [comment]
Hi Harsh! Thanks for using LeafPic :)

Could you upload the GIF / Video to either Google Drive or Dropbox and send us the link?
Also, which page were you on? Albums / All media / opened it from a file explorer?

**Comment by harshmittal2810** [comment]
Hello CalvinNor,
When I open Albums and Navigate to my video folder and try to open that video that time app crashes. I didn't check any other cases.

**Comment by dnldsht** [comment]
may i know somthing more about you device?
does it happen on both video and gifs? or just video?
