### ISSUE TITLE
crash due to a null object reference

### ISSUE THREAD

**Issue by TemporaryAccount0x1** [UnevenSoftware/LeafPic#513]
I'm using f02957610678eb085ea6e9a2c28603f21d95f904
it's hard to reproduce this crash but it happens every now and then.

What I did is click on an image repeatedly and then it crashed. Sometimes when I do it I get no crash.

stack trace:

`App has crashed, executing CustomActivityOnCrash's UncaughtExceptionHandler
                                                                                 java.lang.NullPointerException: Attempt to invoke virtual method 'void org.horaapps.leafpic.activities.SingleMediaActivity.toggleSystemUI()' on a null object reference
                                                                                     at org.horaapps.leafpic.fragments.ImageFragment.lambda$onCreateView$0$ImageFragment(ImageFragment.java:56)
                                                                                     at org.horaapps.leafpic.fragments.ImageFragment$$Lambda$0.onClick(Unknown Source)
                                                                                     at android.view.View.performClick(View.java:5637)
                                                                                     at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$2.onSingleTapConfirmed(SubsamplingScaleImageView.java:540)
                                                                                     at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:300)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                     at android.os.Looper.loop(Looper.java:153)
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:6244)
                                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)`

**Comment by calvinnor** [comment]
@TemporaryAccount0x1 Hello, thanks for using LeafPic!

We'll begin looking for the cause of this issue.

Meanwhile, it would be helpful to us if you could provide your device info like:
- Android OS version
- Manufacturer (Samsung, LG, etc)
- LeafPic version
- Any specific steps to reproduce
- Any specific media that causes this crash

Thank you! :blush:

**Comment by TemporaryAccount0x1** [comment]
Hello @CalvinNor 
this is not necessary I'm certain this crash is caused by this call:
`subsampling.setOnClickListener(view -> ((SingleMediaActivity) getActivity()).toggleSystemUI());`

as of commit fe6a1adf74df6b5a5d8c8b63b071f8efc1eeabe4

that's line 61 in Class `ImageFragment`

Android Studio highlights `getActivity()).toggleSystemUI()` and when you hover over it, it says "method invocation 'toggleSystemUI' may produce NullPointerException.

I'm certain this is what happened so my device information is of no use. This might not happen for every device but it seems like an oversight right now.

**Comment by calvinnor** [comment]
@TemporaryAccount0x1 The problem you found is accurate, it's probably the Activity which is dead and detached from the Fragment, or some other issue, which is causing the NPE.

But it never hurts to have more information about the crash.

Some crashes are reproduced only on certain Android versions & device makes due to SDK changes, so it'll be helpful to analyse the crash further with more data.

Thanks for taking a look :blush:

**Comment by calvinnor** [comment]
Fixed in #528

**Comment by TemporaryAccount0x1** [comment]
@CalvinNor thanks.

btw you can close issues by using one of the keywords in a commit or pull request see:
https://help.github.com/articles/closing-issues-using-keywords/
