### ISSUE TITLE
Print (to printer) not working

### ISSUE THREAD

**Issue by robocop98** [UnevenSoftware/LeafPic#564]
Version: LeafPic (debug) v0.7-alpha1
Print an Image into PDF works very well in this version, but print to printer throws an error.

Mobile phone 1 
- Google Nexus (i9250, "maguro")
- Android 6.0.1
- Lineage 13.0 20180211 NIGHTLY
- rooted
- normally printing with Let's Print Droid (working from other applications)

Mobile phone 2
- Samsung Galaxy SIII (i9300)
- Android 7.1.2
- Lineage 14.1 20180426 NIGHTLY
- rooted
- normally printing with Let's Print Droid (working from other applications)

On both phones I can select my Printer, configured with Let's Print Droid, after few seconds a message appears about "print ... image file" (screenshot to follow) and after this an error notification comes up (screenshot to follow). Unfortunately the error text is not shown in full length and detail, even in panorama view.

EDIT: I cannot upload Screenshots for unknown reasons, just tells me "Something went really wrong, and we can't process that file" for PNG and JPG files.

Text of first message when printing (taken from screenshot):
print_/storage/emulated/0/DCIM/Camera/IMG_20180501_172851.jpg 
Started Print Job print_/storage/emulated/0/DCIM/Camera/IMG_20180501_172851.jpg on HP-LaserJet-1100

Text of error notification (as taken from screenshot):
Druckerfehler(means: print(er) error) print_/storage/emulat..
HP-LaserJet-1100
11:07 am

uriString

**Comment by ghost** [comment]
Thanks for logging the issue.
Could you please share the screen shots via any public image hosting sites like - https://imgur.com/upload

**Comment by robocop98** [comment]
Thanks @nikitasharma536, will remember about public image hosting, but for now will add a logcat excerpt instead. As I can also not attach the log file, I will paste in the content in next comment :)

**Comment by robocop98** [comment]
```
05-07 16:53:27.187  1747  2407 I ActivityManager: START u0 {act=org.horaapps.leafpic.intent.VIEW_ALBUM cmp=org.horaapps.leafpic.debug/org.horaapps.leafpic.activities.SingleMediaActivity (has extras)} from uid 10345 on display 0
05-07 16:53:28.414  7830  7830 I Choreographer: Skipped 50 frames!  The application may be doing too much work on its main thread.
05-07 16:53:28.415  1747  1768 I ActivityManager: Displayed org.horaapps.leafpic.debug/org.horaapps.leafpic.activities.SingleMediaActivity: +1s216ms
05-07 16:53:30.378  1747  1763 I ActivityManager: Waited long enough for: ServiceRecord{2d4a08a u0 com.exlyo.camerarestarter/com.google.firebase.iid.FirebaseInstanceIdService}
05-07 16:53:30.618  1747  1851 E Tuna PowerHAL: Error writing to /sys/devices/system/cpu/cpufreq/interactive/boostpulse: Invalid argument
05-07 16:53:30.643  1747  1888 D AudioService: Stream muted, skip playback
05-07 16:53:30.649  7830  7830 I ListPopupWindow: Could not find method setEpicenterBounds(Rect) on PopupWindow. Oh well.
05-07 16:53:30.698  7830  7830 W art     : Before Android 4.1, method int android.support.v7.widget.DropDownListView.lookForSelectablePosition(int, boolean) would have incorrectly overridden the package-private method in android.widget.ListView
05-07 16:53:30.699  7830  7830 W art     : Before Android 4.1, method int android.support.v7.widget.MenuPopupWindow$MenuDropDownListView.lookForSelectablePosition(int, boolean) would have incorrectly overridden the package-private method in android.widget.ListView
05-07 16:53:39.956  1747  1851 E Tuna PowerHAL: Error writing to /sys/devices/system/cpu/cpufreq/interactive/boostpulse: Invalid argument
05-07 16:53:40.050  1747  1888 D AudioService: Stream muted, skip playback
05-07 16:53:40.187  1747  3669 I ActivityManager: Process com.android.calendar (pid 7694) has died
05-07 16:53:40.187  1747  3669 D ActivityManager: cleanUpApplicationRecord -- 7694
05-07 16:53:40.280  1747  2525 I ActivityManager: Start proc 7867:com.android.printspooler/u0a53 for service com.android.printspooler/.model.PrintSpoolerService
05-07 16:53:40.281  1747  1991 I ActivityManager: START u0 {act=android.print.PRINT_DIALOG dat=printjob:dc9cfca1-6fc1-4a97-8080-8aa697c674c9 cmp=com.android.printspooler/.ui.PrintActivity (has extras)} from uid 1000 on display 0
05-07 16:53:40.601  1747  1758 I ActivityManager: Process com.android.providers.calendar (pid 7700) has died
05-07 16:53:40.602  1747  1758 D ActivityManager: cleanUpApplicationRecord -- 7700
05-07 16:53:40.655  1747  5020 I ActivityManager: Process com.android.deskclock (pid 4546) has died
05-07 16:53:40.655  1747  5020 D ActivityManager: cleanUpApplicationRecord -- 4546
05-07 16:53:40.751  7867  7881 D OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: false
05-07 16:53:40.760  7830  7856 D OpenGLRenderer: endAllStagingAnimators on 0x9db04a00 (MenuPopupWindow$MenuDropDownListView) with handle 0xafbacfa0
05-07 16:53:40.978  7867  7881 W linker  : /system/vendor/lib/hw/gralloc.omap4.so: unused DT entry: type 0xf arg 0x53b
05-07 16:53:40.980  7867  7881 W linker  : /system/vendor/lib/libpvr2d.so: unused DT entry: type 0xf arg 0x767
05-07 16:53:40.985  7867  7881 I OpenGLRenderer: Initialized EGL, version 1.4
05-07 16:53:41.150  1747  1747 I ActivityManager: Start proc 7884:com.blackspruce.lpd/u0a210 for service com.blackspruce.lpd/.KitkatPrintService
05-07 16:53:41.307  7884  7884 W System  : ClassLoader referenced unknown path: /data/app/com.blackspruce.lpd-1/lib/arm
05-07 16:53:41.582  7884  7884 E PrSvc   :  * ** ** onCreate * * * *
05-07 16:53:41.628  7867  7867 I Choreographer: Skipped 33 frames!  The application may be doing too much work on its main thread.
05-07 16:53:41.902  7884  7884 D PrSvc   : LPF Receiver Registered. 
05-07 16:53:41.926  7884  7884 E PrSvc   : * * * * * connected *** ** *** *
05-07 16:53:41.926  7884  7884 D PrSvc   : discovery
05-07 16:53:41.933  1747  1768 I ActivityManager: Displayed com.android.printspooler/.ui.PrintActivity: +1s626ms
05-07 16:53:42.003  7884  7884 E PR-DISC : DISC : construct
05-07 16:53:42.112  7884  7884 E PR-DISC : DISC: start disc. State is CONSTRUCTED
05-07 16:53:42.118  7884  7884 E PR-DISC : DISC : retr exisiting 
05-07 16:53:42.320  7884  7884 E PR-DISC : DISC: start tracking printer 
05-07 16:53:42.486  7867  7900 I MutexFileProvider: Acquired file: /data/user/0/com.android.printspooler/files/print_job_dc9cfca1-6fc1-4a97-8080-8aa697c674c9.pdf by thread: Thread[AsyncTask #2,5,main]
05-07 16:53:42.897  7867  7900 I MutexFileProvider: Released file: /data/user/0/com.android.printspooler/files/print_job_dc9cfca1-6fc1-4a97-8080-8aa697c674c9.pdf from thread: Thread[AsyncTask #2,5,main]
05-07 16:53:42.897  7867  7867 I MutexFileProvider: Acquired file: /data/user/0/com.android.printspooler/files/print_job_dc9cfca1-6fc1-4a97-8080-8aa697c674c9.pdf by thread: Thread[main,5,main]
05-07 16:53:42.915  1747  2659 I ActivityManager: Start proc 7902:com.android.printspooler:renderer/u0i1 for service com.android.printspooler/.renderer.PdfManipulationService
05-07 16:53:43.043  7902  7913 I art     : Background partial concurrent mark sweep GC freed 20718(944KB) AllocSpace objects, 0(0B) LOS objects, 39% free, 6MB/11MB, paused 427us total 110.351ms
05-07 16:53:43.090  7902  7902 W android.content.res.ThemeConfig: Could not get boot theme
05-07 16:53:45.626  7554  7844 W InstanceID/Rpc: No response android.os.ConditionVariable@4ae7837
05-07 16:53:45.714  7554  7844 D FirebaseInstanceId: background sync failed: TIMEOUT, retry in 80s
05-07 16:53:46.405  1747  1851 E Tuna PowerHAL: Error writing to /sys/devices/system/cpu/cpufreq/interactive/boostpulse: Invalid argument
05-07 16:53:46.496  1747  1888 D AudioService: Stream muted, skip playback
05-07 16:53:46.531  7884  7884 E PR-DISC : DISC: stop track
05-07 16:53:46.534  7867  7867 E RecyclerView: No adapter attached; skipping layout
05-07 16:53:46.551  1747  2006 I ActivityManager: Killing 7902:com.android.printspooler:renderer/u0a53i1 (adj 11): isolated not needed
05-07 16:53:46.584  7867  7877 W art     : Suspending all threads took: 7.629ms
05-07 16:53:46.616  7867  7877 I art     : Background partial concurrent mark sweep GC freed 1102(72KB) AllocSpace objects, 2(1772KB) LOS objects, 39% free, 10MB/17MB, paused 34.820ms total 110.076ms
05-07 16:53:46.619  7884  7884 D PrSvc   : job queued
05-07 16:53:46.634  1747  2378 D ActivityManager: cleanUpApplicationRecord -- 7902
05-07 16:53:46.701  1747  1747 D ZenLog  : intercepted: 0|com.android.printspooler|0|null|10053,alarmsOnly
05-07 16:53:46.701  1747  1747 V NotificationService: pkg=com.android.printspooler canInterrupt=false intercept=true
05-07 16:53:46.753  1747  1747 D ZenLog  : intercepted: 0|android|17039424|null|1000,alarmsOnly
05-07 16:53:46.754  1747  1747 V NotificationService: pkg=android canInterrupt=false intercept=true
05-07 16:53:46.781  1747  2659 W ActivityManager: Duplicate finish request for ActivityRecord{20fefde u0 com.android.printspooler/.ui.PrintActivity t897 f}
05-07 16:53:46.792  1747  1747 V NotificationService: pkg=com.android.printspooler canInterrupt=false intercept=true
05-07 16:53:46.895  7884  7884 W System.err: java.io.FileNotFoundException: /storage/emulated/0/LPD/print_/storage/emulated/0/Pictures/Screenshots/Screenshot_20180506-111243.png.pdf: open failed: ENOENT (No such file or directory)
05-07 16:53:46.917  7884  7884 W System.err:    at libcore.io.IoBridge.open(IoBridge.java:452)
05-07 16:53:46.917  7884  7884 W System.err:    at java.io.FileOutputStream.<init>(FileOutputStream.java:87)
05-07 16:53:46.917  7884  7884 W System.err:    at java.io.FileOutputStream.<init>(FileOutputStream.java:72)
05-07 16:53:46.917  7884  7884 W System.err:    at com.blackspruce.lpd.KitkatPrintService.localizeFile(KitkatPrintService.java:208)
05-07 16:53:46.917  7884  7884 W System.err:    at com.blackspruce.lpd.KitkatPrintService.onPrintJobQueued(KitkatPrintService.java:150)
05-07 16:53:46.917  7884  7884 W System.err:    at android.printservice.PrintService$ServiceHandler.handleMessage(PrintService.java:540)
05-07 16:53:46.917  7884  7884 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:102)
05-07 16:53:46.917  7884  7884 W System.err:    at android.os.Looper.loop(Looper.java:148)
05-07 16:53:46.917  7884  7884 W System.err:    at android.app.ActivityThread.main(ActivityThread.java:5461)
05-07 16:53:46.917  7884  7884 W System.err:    at java.lang.reflect.Method.invoke(Native Method)
05-07 16:53:46.917  7884  7884 W System.err:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
05-07 16:53:46.917  7884  7884 W System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
05-07 16:53:46.917  7884  7884 W System.err: Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
05-07 16:53:46.922  7884  7884 W System.err:    at libcore.io.Posix.open(Native Method)
05-07 16:53:46.922  7884  7884 W System.err:    at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
05-07 16:53:46.922  7884  7884 W System.err:    at libcore.io.IoBridge.open(IoBridge.java:438)
05-07 16:53:46.922  7884  7884 W System.err:    ... 11 more
05-07 16:53:46.963  1747  1747 V NotificationService: pkg=com.android.printspooler canInterrupt=false intercept=true
05-07 16:53:46.967  7884  7884 E PrSvc   : Print Job Exception
05-07 16:53:46.967  7884  7884 E PrSvc   : java.lang.NullPointerException: uriString
05-07 16:53:46.967  7884  7884 E PrSvc   :      at android.net.Uri$StringUri.<init>(Uri.java:475)
05-07 16:53:46.967  7884  7884 E PrSvc   :      at android.net.Uri$StringUri.<init>(Uri.java)
05-07 16:53:46.967  7884  7884 E PrSvc   :      at android.net.Uri.parse(Uri.java:437)
05-07 16:53:46.967  7884  7884 E PrSvc   :      at com.blackspruce.lpd.KitkatPrintService.onPrintJobQueued(KitkatPrintService.java:153)
05-07 16:53:46.967  7884  7884 E PrSvc   :      at android.printservice.PrintService$ServiceHandler.handleMessage(PrintService.java:540)
05-07 16:53:46.967  7884  7884 E PrSvc   :      at android.os.Handler.dispatchMessage(Handler.java:102)
05-07 16:53:46.967  7884  7884 E PrSvc   :      at android.os.Looper.loop(Looper.java:148)
05-07 16:53:46.967  7884  7884 E PrSvc   :      at android.app.ActivityThread.main(ActivityThread.java:5461)
05-07 16:53:46.967  7884  7884 E PrSvc   :      at java.lang.reflect.Method.invoke(Native Method)
05-07 16:53:46.967  7884  7884 E PrSvc   :      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
05-07 16:53:46.967  7884  7884 E PrSvc   :      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
05-07 16:53:47.037  7884  7884 E PR-DISC : DISC: stop discovery
05-07 16:53:47.039  1747  1747 V NotificationService: pkg=com.android.printspooler canInterrupt=false intercept=true
05-07 16:53:47.044  7884  7884 E PR-DISC :  DISC: destroy
05-07 16:53:47.063  7884  7918 D OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: false
05-07 16:53:47.071  7884  7884 D PrSvc   :  * ** ** disconnected * * * *
05-07 16:53:47.071  7884  7884 E PrSvc   :  * ** ** onDestroy * * * *
05-07 16:53:47.187  7884  7918 W linker  : /system/vendor/lib/hw/gralloc.omap4.so: unused DT entry: type 0xf arg 0x53b
05-07 16:53:47.187  7884  7918 W linker  : /system/vendor/lib/hw/gralloc.omap4.so: is missing DT_SONAME will use basename as a replacement: "gralloc.omap4.so"
05-07 16:53:47.190  7884  7918 W linker  : /system/vendor/lib/libpvr2d.so: unused DT entry: type 0xf arg 0x767
05-07 16:53:47.190  7884  7918 W linker  : /system/vendor/lib/libpvr2d.so: is missing DT_SONAME will use basename as a replacement: "libpvr2d.so"
05-07 16:53:47.194  7884  7918 I OpenGLRenderer: Initialized EGL, version 1.4
05-07 16:53:47.348  7884  7918 V RenderScript: 0xa149d000 Launching thread(s), CPUs 2
05-07 16:53:50.824  1747  1881 D ConnectivityService: notifyType CAP_CHANGED for NetworkAgentInfo [WIFI () - 208]
05-07 16:53:52.962  1747  1768 E Tuna PowerHAL: Error writing to /sys/devices/system/cpu/cpufreq/interactive/boostpulse: Invalid argument
05-07 16:53:56.866  1747  1881 D ConnectivityService: notifyType CAP_CHANGED for NetworkAgentInfo [WIFI () - 208]
05-07 16:53:58.797  1747  7093 D NetlinkSocketObserver: NeighborEvent{elapsedMs=159192295, fe80::1, [84A8E4670BB4], RTM_NEWNEIGH, NUD_STALE}
```
